# Generated by Django 6.1.1 on 2026-09-22 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('class_content', models.TextField(verbose_name='conteúdo da aula')),
                ('learned_notes', models.TextField(verbose_name='o que eu aprendi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('ready', 'Pronto'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('raw_model_response', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='study.lesson')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('mcq', 'Múltipla escolha'), ('cloze', 'Lacuna'), ('scenario', 'Cenário')], default='mcq', max_length=20)),
                ('topic', models.CharField(blank=True, max_length=80)),
                ('prompt', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('correct_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('correct_values', models.JSONField(blank=True, default=list)),
                ('explanation', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='study.quiz')),
            ],
            options={
                'ordering': ['kind', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ids', models.JSONField(default=list)),
                ('answers', models.JSONField(blank=True, default=list)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('phase_scores', models.JSONField(blank=True, default=list)),
                ('study_plan', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('in_progress', 'Em andamento'), ('completed', 'Concluída')], default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='study.quiz')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
